export const fruitsWithoutDiffForms = [
    { category_id: 2, first_name: "combo" },
    { category_id: 2, first_name: "banana" },
    { category_id: 2, first_name: "coconut" },
    { category_id: 2, first_name: "orange" },
    { category_id: 2, first_name: "strawberry" },
    { category_id: 2, first_name: "grapes" },
    { category_id: 2, first_name: "pineapple" },
    { category_id: 2, first_name: "apple ber" },
    { category_id: 2, first_name: "apple" },
    { category_id: 2, first_name: "chikoo" },
    { category_id: 2, first_name: "pomegranate" },
    { category_id: 2, first_name: "papaya" },
    { category_id: 2, first_name: "watermelon" },
    { category_id: 2, first_name: "groundnuts" },
    { category_id: 2, first_name: "guava" },
    { category_id: 2, first_name: "mango" },
    { category_id: 2, first_name: "tamarind" },
    { category_id: 2, first_name: "blueberry" },
    { category_id: 2, first_name: "dragon fruit" },
    { category_id: 2, first_name: "kiwi" },
    { category_id: 2, first_name: "fig" },
    { category_id: 2, first_name: "mosambi" },
    { category_id: 2, first_name: "muskmelon" },
    { category_id: 2, first_name: "avocado" },
    { category_id: 2, first_name: "sugarcane" },
    { category_id: 2, first_name: "cherry" },
    { category_id: 2, first_name: "gooseberry" },
    { category_id: 2, first_name: "grapefruit" },
    { category_id: 2, first_name: "raspberry" },
    { category_id: 2, first_name: "passion fruit" },
    { category_id: 2, first_name: "pear" },
    { category_id: 2, first_name: "rasbhari" },
    { category_id: 2, first_name: "betel nut" },
    { category_id: 2, first_name: "star fruit" },
]