export const fruitsWithoutDiffForms = [
    { category_id: 2, first_name: "Banana" },
    { category_id: 2, first_name: "Coconut" },
    { category_id: 2, first_name: "Orange" },
    { category_id: 2, first_name: "Strawberry" },
    { category_id: 2, first_name: "Grapes" },
    { category_id: 2, first_name: "Apple" },
    { category_id: 2, first_name: "apple ber" },
    { category_id: 2, first_name: "Pineapple" },
    { category_id: 2, first_name: "Chikoo" },
    { category_id: 2, first_name: "Pomegranate" },
    { category_id: 2, first_name: "Papaya" },
    { category_id: 2, first_name: "Watermelon" },
    { category_id: 2, first_name: "Groundnuts" },
    { category_id: 2, first_name: "Guava" },
    { category_id: 2, first_name: "Mango" },
    { category_id: 2, first_name: "Tamarind" },
    { category_id: 2, first_name: "Blueberry" },
    { category_id: 2, first_name: "Dragon Fruit" },
    { category_id: 2, first_name: "Kiwi" },
    { category_id: 2, first_name: "Fig" },
    { category_id: 2, first_name: "mosambi" },
    { category_id: 2, first_name: "Muskmelon" },
    { category_id: 2, first_name: "Avocado" },
    { category_id: 2, first_name: "Sugarcane" },
    { category_id: 2, first_name: "Cherry" },
    { category_id: 2, first_name: "Gooseberry" },
    { category_id: 2, first_name: "Grapefruit" },
    { category_id: 2, first_name: "Raspberry" },
    { category_id: 2, first_name: "Passion Fruit" },
    { category_id: 2, first_name: "Pear" },
    { category_id: 2, first_name: "rasbhari" },
    { category_id: 2, first_name: "betel nut" },
    { category_id: 2, first_name: "Star Fruit" },
]