export const fruitsWithoutDiffForms = [
    { name: "Banana" },
    { name: "Coconut" },
    { name: "Orange" },
    { name: "Strawberry" },
    { name: "Grapes" },
    { name: "Apple" },
    { name: "apple ber" },
    { name: "Pineapple" },
    { name: "Chikoo" },
    { name: "Pomegranate" },
    { name: "Papaya" },
    { name: "Watermelon" },
    { name: "Groundnuts" },
    { name: "Guava" },
    { name: "Mango" },
    { name: "Tamarind" },
    { name: "Blueberry" },
    { name: "Dragon Fruit" },
    { name: "Kiwi" },
    { name: "Fig" },
    { name: "mosambi" },
    { name: "Muskmelon" },
    { name: "Avocado" },
    { name: "Sugarcane" },
    { name: "Cherry" },
    { name: "Gooseberry" },
    { name: "Grapefruit" },
    { name: "Raspberry" },
    { name: "Passion Fruit" },
    { name: "Pear" },
    { name: "rasbhari" },
    { name: "betel nut" },
    { name: "Star Fruit" },
]