export const vegetablesWithoutDiffForms = [
    { category_id: 1, first_name: "chilli" },
    { category_id: 1, first_name: "onion" },
    { category_id: 1, first_name: "cauliflower" },
    { category_id: 1, first_name: "potato" },
    { category_id: 1, first_name: "green peas" },
    { category_id: 1, first_name: "cabbage" },
    { category_id: 1, first_name: "beetroot" },
    { category_id: 1, first_name: "lady finger" },
    { category_id: 1, first_name: "gourd" },
    { category_id: 1, first_name: "brinjal" },
    { category_id: 1, first_name: "sweet potato" },
    { category_id: 1, first_name: "turnip" },
    { category_id: 1, first_name: "banana" },
    { category_id: 1, first_name: "lotus stem" },
    { category_id: 1, first_name: "broccoli" },
    { category_id: 1, first_name: "spinach" },
    { category_id: 1, first_name: "fenugreek" },
    { category_id: 1, first_name: "tomato" },
    { category_id: 1, first_name: "ginger" },
    { category_id: 1, first_name: "carrot" },
    { category_id: 1, first_name: "capsicum" },
    { category_id: 1, first_name: "lemon" },
    { category_id: 1, first_name: "cucumber" },
    { category_id: 1, first_name: "beans" },
    { category_id: 1, first_name: "mushroom" },
    { category_id: 1, first_name: "garlic" },
    { category_id: 1, first_name: "spring garlic" },
    { category_id: 1, first_name: "radish" },
    { category_id: 1, first_name: "turmeric" },
    { category_id: 1, first_name: "arvi" },
    { category_id: 1, first_name: "drumstick" },
    { category_id: 1, first_name: "knol khol" },
    { category_id: 1, first_name: "pumpkin" },
    { category_id: 1, first_name: "coriander" },
    { category_id: 1, first_name: "sprouts" },
    { category_id: 1, first_name: "bell pepper" },
    { category_id: 1, first_name: "lettuce" },
    { category_id: 1, first_name: "leave" },
    { category_id: 1, first_name: "zucchini" },
    { category_id: 1, first_name: "jackfruit" },
    { category_id: 1, first_name: "rosemary" },
    { category_id: 1, first_name: "peas" },
    { category_id: 1, first_name: "groundnut" },
    { category_id: 1, first_name: "parsley" },
    { category_id: 1, first_name: "bok choy" },
    { category_id: 1, first_name: "Chenopodium" },
    { category_id: 1, first_name: "thyme" },
    { category_id: 1, first_name: "amla" },
    { category_id: 1, first_name: "tinda" },
    { category_id: 1, first_name: "giloy" },
    { category_id: 1, first_name: "tinda" },
    { category_id: 1, first_name: "hara chana saag" },
    { category_id: 1, first_name: "yam" },
    { category_id: 1, first_name: "butternut" },
    { category_id: 1, first_name: "shami patra" },
    { category_id: 1, first_name: "coccinia" },
    { category_id: 1, first_name: "colocasia" },
    { category_id: 1, first_name: "corn" }
]
