// NOTE: pointed gaurd in zepto is parwal

export const productsWithoutDiffForms = [
    { "name": "chilli" },
    { "name": "onion" },
    { "name": "cauliflower" },
    { "name": "potato" },
    { "name": "green peas" },
    { "name": "cabbage" },
    { "name": "beetroot" },
    { "name": "lady finger" },
    { "name": "gourd" },
    { "name": "brinjal" },
    { "name": "sweet potato" },
    { "name": "turnip" },
    { "name": "banana" },
    { "name": "lotus stem" },
    { "name": "broccoli" },
    { "name": "spinach" },
    { "name": "fenugreek" },
    { "name": "tomato" },
    { "name": "ginger" },
    { "name": "carrot" },
    { "name": "capsicum" },
    { "name": "lemon" },
    { "name": "cucumber" },
    { "name": "beans" },
    { "name": "mushroom" },
    { "name": "garlic" },
    { "name": "spring garlic" },
    { "name": "radish" },
    { "name": "turmeric" },
    { "name": "arvi" },
    { "name": "drumstick" },
    { "name": "knol khol" },
    { "name": "pumpkin" },
    { "name": "coriander" },
    { "name": "sprouts" },
    { "name": "bell pepper" },
    { "name": "lettuce" },
    { "name": "leave" },
    { "name": "zucchini" },
    { "name": "jackfruit" },
    { "name": "rosemary" },
    { "name": "peas" },
    { "name": "groundnut" },
    { "name": "parsley" },
    { "name": "bok choy" },
    { "name": "Chenopodium" },
    { "name": "thyme" },
    { "name": "amla" },
    { "name": "tinda" },
    { "name": "giloy" },
    { "name": "tinda" },
    { "name": "hara chana saag" },
    { "name": "yam" },
    { "name": "butternut" },
    { "name": "shami patra" },
    { "name": "coccinia" },
    { "name": "colocasia" },
    { "name": "corn" }
]

console.log(productsWithoutDiffForms.length);
